package hu.elte.csapat4.models.map;

public enum ActionType {
    ATTACK, DRAGON_BREATH,
    MOVE,
    PRODUCE,
    BUILD_FARM, BUILD_MINE, BUILD_CABIN, BUILD_BASTION,
    CREATE_WORKER,CREATE_KNIGHT, CREATE_ARMORED, CREATE_PITCHFORK, CREATE_DRAGON

}
